// ISO 3166 country codes as the trade.gov.am portal lists them (box 34/15 origin & departure
// country → ESADout_CU `OriginCountryCode` / `DispatchCountryCode`). The portal keys on the
// 2-letter CODE, so the dropdown value is the code; the Armenian name is display + written
// alongside as `*CountryName`. Generated from the portal's own dropdown export.
const COUNTRY_CODE_OPTIONS = [
  { value: "", label: "—" },
  { value: "00", label: "00 — ԵՐԿԻՐՆ ԱՆՀԱՅՏ Է" },
  { value: "AD", label: "AD — ԱՆԴՈՐՐԱ" },
  { value: "AE", label: "AE — ԱՐԱԲ.ՄԻԱՑ.ԷՄԻՐՈՒԹ." },
  { value: "AF", label: "AF — ԱՖՂԱՆՍՏԱՆ" },
  { value: "AG", label: "AG — ԱՆՏԻԳՈՒԱ.ԲԱՐԲ." },
  { value: "AI", label: "AI — ԱՆԳԻԼՅԱ" },
  { value: "AL", label: "AL — ԱԼԲԱՆԻԱ" },
  { value: "AM", label: "AM — ՀԱՅԱՍՏԱՆ" },
  { value: "AO", label: "AO — ԱՆԳՈԼԱ" },
  { value: "AQ", label: "AQ — ԱՆՏԱՐԿՏԻԴԱ" },
  { value: "AR", label: "AR — ԱՐԳԵՆՏԻՆԱ" },
  { value: "AS", label: "AS — ԱՐԵՒԵԼՅԱՆ ՍԱՄՈԱ (ԱՄՆ)" },
  { value: "AT", label: "AT — ԱՎՍՏՐԻԱ" },
  { value: "AU", label: "AU — ԱՎՍՏՐԱԼԻԱ" },
  { value: "AW", label: "AW — ԱՐՈՒԲԱ" },
  { value: "AX", label: "AX — ԱԼԱՆԴՅԱՆ ԿՂԶԻՆԵՐ" },
  { value: "AZ", label: "AZ — ԱԴՐԲԵՋԱՆ" },
  { value: "BA", label: "BA — ԲՈՍՆԻԱ ԵՒ ՀԵՐՑԵԳՈՎԻՆԱ" },
  { value: "BB", label: "BB — ԲԱՐԲԱԴՈՍ" },
  { value: "BD", label: "BD — ԲԱՆԳԼԱԴԵՇ" },
  { value: "BE", label: "BE — ԲԵԼԳԻԱ" },
  { value: "BF", label: "BF — ԲՈՒՐԿԻՆԱ-ՖԱՍՈ" },
  { value: "BG", label: "BG — ԲՈՒԼՂԱՐԻԱ" },
  { value: "BH", label: "BH — ԲԱՀՐԵՅՆ" },
  { value: "BI", label: "BI — ԲՈՒՐՈՒՆԴԻ" },
  { value: "BJ", label: "BJ — ԲԵՆԻՆ" },
  { value: "BL", label: "BL — ՍԵՆ ԲԱՐՏԵԼՄԻ" },
  { value: "BM", label: "BM — ԲԵՐՄՈՒԴՅԱՆ ԿՂԶԻՆԵՐ" },
  { value: "BN", label: "BN — ԲՐՈՒՆԵՅ" },
  { value: "BO", label: "BO — ԲՈԼԻՎԻԱ" },
  { value: "BQ", label: "BQ — ԲՈՆԱՅՐԵ, ՍԱԲԱ և ՍԻՆՏ ԷՍՏԱՏԻՈՒՍ" },
  { value: "BR", label: "BR — ԲՐԱԶԻԼԻԱ" },
  { value: "BS", label: "BS — ԲԱՀԱՄՅԱՆ ԿՂԶԻՆԵՐ" },
  { value: "BT", label: "BT — ԲՈՒԹԱՆ" },
  { value: "BV", label: "BV — ԲՈՒՎԵ" },
  { value: "BW", label: "BW — ԲՈՏՍՎԱՆԱ" },
  { value: "BY", label: "BY — ԲԵԼԱՌՈՒՍ" },
  { value: "BZ", label: "BZ — ԲԵԼԻԶ" },
  { value: "CA", label: "CA — ԿԱՆԱԴԱ" },
  { value: "CC", label: "CC — ԿՈԿՈՍՅԱՆ ԿՂԶԻՆԵՐ" },
  { value: "CD", label: "CD — ԿՈՆԳՈ (ԿԴՀ)" },
  { value: "CF", label: "CF — ԿԵՆՏ.ԱՖՐ.ՀԱՆՐ." },
  { value: "CG", label: "CG — ԿՈՆԳՈ" },
  { value: "CH", label: "CH — ՇՎԵՅՑԱՐԻԱ" },
  { value: "CI", label: "CI — ԿՈՏ Դ'ԻՎՈՒԱՐ" },
  { value: "CK", label: "CK — ԿՈՒԿԻ ԿՂԶ." },
  { value: "CL", label: "CL — ՉԻԼԻ" },
  { value: "CM", label: "CM — ԿԱՄԵՐՈՒՆ" },
  { value: "CN", label: "CN — ՉԻՆԱՍՏԱՆ" },
  { value: "CO", label: "CO — ԿՈԼՈՒՄԲԻԱ" },
  { value: "CR", label: "CR — ԿՈՍՏԱ ՌԻԿԱ" },
  { value: "CU", label: "CU — ԿՈՒԲԱ" },
  { value: "CV", label: "CV — ԿԱԲՈ-ՎԵՐԴԵ" },
  { value: "CW", label: "CW — ԿՅՈՒՐԱՍԱՈ" },
  { value: "CX", label: "CX — ԾՆՆԴՅԱՆ ԿՂԶ." },
  { value: "CY", label: "CY — ԿԻՊՐՈՍ" },
  { value: "CZ", label: "CZ — ՉԵԽԻԱ" },
  { value: "DE", label: "DE — ԳԵՐՄԱՆԻԱ" },
  { value: "DJ", label: "DJ — ՋԻԲՈՒԹԻ" },
  { value: "DK", label: "DK — ԴԱՆԻԱ" },
  { value: "DM", label: "DM — ԴՈՄԻՆԻԿԱ" },
  { value: "DO", label: "DO — ԴՈՄԻՆԻԿՅԱՆ ՀԱՆՐ." },
  { value: "DZ", label: "DZ — ԱԼԺԻՐ" },
  { value: "EC", label: "EC — ԷԿՎԱԴՈՐ" },
  { value: "EE", label: "EE — ԷՍՏՈՆԻԱ" },
  { value: "EG", label: "EG — ԵԳԻՊՏՈՍ" },
  { value: "EH", label: "EH — ԱՐԵՒՄՏՅԱՆ ՍԱՀԱՐԱ" },
  { value: "ER", label: "ER — ԷՐԻԹՐԵԱ" },
  { value: "ES", label: "ES — ԻՍՊԱՆԻԱ" },
  { value: "ET", label: "ET — ԵԹՈՎՊԻԱ" },
  { value: "EU", label: "EU — ԵՎՐՈՊԱԿԱՆ ՄԻՈՒԹՅՈՒՆ" },
  { value: "FI", label: "FI — ՖԻՆԼԱՆԴԻԱ" },
  { value: "FJ", label: "FJ — ՖԻՋԻ" },
  { value: "FK", label: "FK — ՖՈԼԿԼԵՆԴՅԱՆ ԿՂԶ." },
  { value: "FM", label: "FM — ՄԻԿՐՈՆԵԶԻԱ" },
  { value: "FO", label: "FO — ՖԱՐԵՐՅԱՆ ԿՂԶ." },
  { value: "FR", label: "FR — ՖՐԱՆՍԻԱ" },
  { value: "GA", label: "GA — ԳԱԲՈՆ" },
  { value: "GB", label: "GB — ՄԵԾ ԲՐԻՏԱՆԻԱ" },
  { value: "GD", label: "GD — ԳՐԵՆԱԴԱ" },
  { value: "GE", label: "GE — ՎՐԱՍՏԱՆ" },
  { value: "GF", label: "GF — ԳՎԻԱՆԱ" },
  { value: "GG", label: "GG — ԳԵՐՆՍԻ" },
  { value: "GH", label: "GH — ԳԱՆԱ" },
  { value: "GI", label: "GI — ՋԻԲՐԱԼԹԱՐ" },
  { value: "GL", label: "GL — ԳՐԵՆԼԱՆԴԻԱ" },
  { value: "GM", label: "GM — ԳԱՄԲԻԱ" },
  { value: "GN", label: "GN — ԳՎԻՆԵԱ" },
  { value: "GP", label: "GP — ԳՎԱԴԵԼՈՒՊԱ" },
  { value: "GQ", label: "GQ — ՀԱՍԱՐԱԿԱԾԱՅԻՆ ԳՎԻՆԵԱ" },
  { value: "GR", label: "GR — ՀՈՒՆԱՍՏԱՆ" },
  { value: "GS", label: "GS — ՀԱՐԱՎԱՅԻՆ ՋՈՐՋԻԱ ԵՒ Հ. ՍԵՆԴՎԻՉ. ԿՂԶԻՆԵՐ" },
  { value: "GT", label: "GT — ԳՎԱՏԵՄԱԼԱ" },
  { value: "GU", label: "GU — ԳՈՒԱՄ (ԱՄՆ)" },
  { value: "GW", label: "GW — ԳՎԻՆԵԱ-ԲԻՍԱՈՒ" },
  { value: "GY", label: "GY — ԳԱՅԱՆԱ" },
  { value: "HK", label: "HK — ՍՅԱՆԳԱՆ (ՀՈՆԿՈՆԳ)" },
  { value: "HM", label: "HM — ԽԵՐԴ ԵՒ ՄԱԿԴՈՆԱԼԴ" },
  { value: "HN", label: "HN — ՀՈՆԴՈՒՐԱՍ" },
  { value: "HR", label: "HR — ԽՈՐՎԱԹԻԱ" },
  { value: "HT", label: "HT — ՀԱԻԹԻ" },
  { value: "HU", label: "HU — ՀՈՒՆԳԱՐԻԱ" },
  { value: "ID", label: "ID — ԻՆԴՈՆԵԶԻԱ" },
  { value: "IE", label: "IE — ԻՌԼԱՆԴԻԱ" },
  { value: "IL", label: "IL — ԻՍՐԱՅԵԼ" },
  { value: "IM", label: "IM — ՄԵՆ ԿՂԶ." },
  { value: "IN", label: "IN — ՀՆԴԿԱՍՏԱՆ" },
  { value: "IO", label: "IO — ԲՐԻՏ.ՏԱՐ.ՀՆԴ.ՕՎԿ." },
  { value: "IQ", label: "IQ — ԻՐԱՔ" },
  { value: "IR", label: "IR — ԻՐԱՆ" },
  { value: "IS", label: "IS — ԻՍԼԱՆԴԻԱ" },
  { value: "IT", label: "IT — ԻՏԱԼԻԱ" },
  { value: "JE", label: "JE — ՋԵՐՍԻ" },
  { value: "JM", label: "JM — ՃԱՄԱՅԿԱ" },
  { value: "JO", label: "JO — ՀՈՐԴԱՆԱՆ" },
  { value: "JP", label: "JP — ՃԱՊՈՆԻԱ" },
  { value: "KE", label: "KE — ՔԵՆԻԱ" },
  { value: "KG", label: "KG — ՂՐՂԶՍՏԱՆ" },
  { value: "KH", label: "KH — ԿԱՄԲՈՋԱ" },
  { value: "KI", label: "KI — ԿԻՐԻԲԱՏԻ" },
  { value: "KM", label: "KM — ԿՈՄՈՐՅԱՆ ԿՂԶԻՆԵՐ" },
  { value: "KN", label: "KN — ՍԵՆՏ-ԿԻՏՍ ԵՒ ՆԵՎԻՍ" },
  { value: "KP", label: "KP — ԿՈՐԵԱ (ԿԺԴՀ)" },
  { value: "KR", label: "KR — ԿՈՐԵԱՅԻ ՀԱՆՐԱՊԵՏ." },
  { value: "KW", label: "KW — ՔՈՒՎԵՅԹ" },
  { value: "KY", label: "KY — ԿԱՅՄԱՆԻ ԿՂԶ." },
  { value: "KZ", label: "KZ — ՂԱԶԱԽՍՏԱՆ" },
  { value: "LA", label: "LA — ԼԱՈՍ" },
  { value: "LB", label: "LB — ԼԻԲԱՆԱՆ" },
  { value: "LC", label: "LC — ՍԵՆՏ-ԼՅՈՒՍԻԱ" },
  { value: "LI", label: "LI — ԼԻԽՏԵՆՇՏԵՅՆ" },
  { value: "LK", label: "LK — ՇՐԻ-ԼԱՆԿԱ" },
  { value: "LR", label: "LR — ԼԻԲԵՐԻԱ" },
  { value: "LS", label: "LS — ԼԵՍՈՏՈ" },
  { value: "LT", label: "LT — ԼԻՏՎԱ" },
  { value: "LU", label: "LU — ԼՅՈՒՔՍԵՄԲՈՒՐԳ" },
  { value: "LV", label: "LV — ԼԱՏՎԻԱ" },
  { value: "LY", label: "LY — ԼԻԲԻԱ" },
  { value: "MA", label: "MA — ՄԱՐՈԿԿՈ" },
  { value: "MC", label: "MC — ՄՈՆԱԿՈ" },
  { value: "MD", label: "MD — ՄՈԼԴՈՎԱ" },
  { value: "ME", label: "ME — ՄՈՆՏԵՆԵԳՐՈ" },
  { value: "MF", label: "MF — ՍԵՆ ՄԱՐՏԵՆ (ՖՐ.)" },
  { value: "MG", label: "MG — ՄԱԴԱԳԱՍԿԱՐ" },
  { value: "MH", label: "MH — ՄԱՐՇԱԼՅԱՆ ԿՂԶ." },
  { value: "MK", label: "MK — ՀՅՈՒՍԻՍԱՅԻՆ ՄԱԿԵԴՈՆԻԱ" },
  { value: "ML", label: "ML — ՄԱԼԻ" },
  { value: "MM", label: "MM — ՄՅԱՆՄԱ" },
  { value: "MN", label: "MN — ՄՈՆՂՈԼԻԱ" },
  { value: "MO", label: "MO — ԱՈՄԻՆ" },
  { value: "MP", label: "MP — ՄԱՐԻԱՆՅԱՆ ԿՂԶԻՆԵՐ" },
  { value: "MQ", label: "MQ — ՄԱՐՏԻՆԻԿԱ" },
  { value: "MR", label: "MR — ՄԱՎՐԻՏԱՆԻԱ" },
  { value: "MS", label: "MS — ՄՈՆՏՍԵՐԱՏ" },
  { value: "MT", label: "MT — ՄԱԼԹԱ" },
  { value: "MU", label: "MU — ՄԱՎՐԻԿԻՈՍ" },
  { value: "MV", label: "MV — ՄԱԼԴԻՎՅԱՆ ԿՂԶ." },
  { value: "MW", label: "MW — ՄԱԼԱՎԻ" },
  { value: "MX", label: "MX — ՄԵՔՍԻԿԱ" },
  { value: "MY", label: "MY — ՄԱԼԱՅԶԻԱ" },
  { value: "MZ", label: "MZ — ՄՈԶԱՄԲԻԿ" },
  { value: "NA", label: "NA — ՆԱՄԻԲԻԱ" },
  { value: "NC", label: "NC — ՆՈՐ ԿԱԼԵԴՈՆԻԱ" },
  { value: "NE", label: "NE — ՆԻԳԵՐ" },
  { value: "NF", label: "NF — ՆՈՐՖՈԼԿ" },
  { value: "NG", label: "NG — ՆԻԳԵՐԻԱ" },
  { value: "NI", label: "NI — ՆԻԿԱՐԱԳՈՒԱ" },
  { value: "NL", label: "NL — ՆԻԴԵՌԼԱՆԴՆԵՐ" },
  { value: "NO", label: "NO — ՆՈՐՎԵԳԻԱ" },
  { value: "NP", label: "NP — ՆԵՊԱԼ" },
  { value: "NR", label: "NR — ՆԱՈՒՐՈՒ" },
  { value: "NU", label: "NU — ՆԻՈՒԵ" },
  { value: "NZ", label: "NZ — ՆՈՐ ԶԵԼԱՆԴԻԱ" },
  { value: "OM", label: "OM — ՕՄԱՆ" },
  { value: "PA", label: "PA — ՊԱՆԱՄԱ" },
  { value: "PE", label: "PE — ՊԵՐՈՒ" },
  { value: "PF", label: "PF — ՖՐ.ՊՈԼԻՆԵԶԻԱ" },
  { value: "PG", label: "PG — ՊԱՊՈՒԱ ՆՈՐ ԳՎԻՆԵԱ" },
  { value: "PH", label: "PH — ՖԻԼԻՊԻՆՆԵՐ" },
  { value: "PK", label: "PK — ՊԱԿԻՍՏԱՆ" },
  { value: "PL", label: "PL — ԼԵՀԱՍՏԱՆ" },
  { value: "PM", label: "PM — ՍԵՆ-ՊՅԵՐ ԵՒ ՄԻԿԵԼՈՆ" },
  { value: "PN", label: "PN — ՊԻՏԿԵՐՆ" },
  { value: "PR", label: "PR — ՊՈՒԵՐՏՈ ՌԻԿՈ" },
  { value: "PS", label: "PS — ՊԱՂԵՍՏԻՆ, ՕԿՈՒՊԱՑՎԱԾ" },
  { value: "PT", label: "PT — ՊՈՐՏՈՒԳԱԼԻԱ" },
  { value: "PW", label: "PW — ՊԱԼԱՈՒ" },
  { value: "PY", label: "PY — ՊԱՐԱԳՎԱՅ" },
  { value: "QA", label: "QA — ԿԱՏԱՐ" },
  { value: "RE", label: "RE — ՌԵՅՈՒՆՅՈՆ" },
  { value: "RO", label: "RO — ՌՈՒՄԻՆԻԱ" },
  { value: "RS", label: "RS — ՍԵՐԲԻԱ" },
  { value: "RU", label: "RU — ՌՈՒՍԱՍՏԱՆ" },
  { value: "RW", label: "RW — ՌՈՒԱՆԴԱ" },
  { value: "SA", label: "SA — ՍԱՈՒԴՅԱՆ ԱՐԱԲԻԱ" },
  { value: "SB", label: "SB — ՍՈՂՈՄՈՆՅԱՆ ԿՂԶ." },
  { value: "SC", label: "SC — ՍԵՅՇԵԼՅԱՆ ԿՂԶ." },
  { value: "SD", label: "SD — ՍՈՒԴԱՆ" },
  { value: "SE", label: "SE — ՇՎԵԴԻԱ" },
  { value: "SG", label: "SG — ՍԻՆԳԱՊՈՒՐ" },
  { value: "SH", label: "SH — ՍՈՒՐԲ ՀԵՂԻՆԵԻ ԿՂԶ." },
  { value: "SI", label: "SI — ՍԼՈՎԵՆԻԱ" },
  { value: "SJ", label: "SJ — ՇՊԻՑԲԵՐԳԵՆ ԵՒ ՅԱՆՄԱՅԼԵՆ" },
  { value: "SK", label: "SK — ՍԼՈՎԱԿԻԱ" },
  { value: "SL", label: "SL — ՍՅԵՌԱ ԼԵՈՆԵ" },
  { value: "SM", label: "SM — ՍԱՆ-ՄԱՐԻՆՈ" },
  { value: "SN", label: "SN — ՍԵՆԵԳԱԼ" },
  { value: "SO", label: "SO — ՍՈՄԱԼԻ" },
  { value: "SR", label: "SR — ՍՈՒՐԻՆԱՄ" },
  { value: "SS", label: "SS — ՀԱՐԱՎԱՅԻՆ ՍՈՒԴԱՆ" },
  { value: "ST", label: "ST — ՍԱՆ-ՏՈՄԵ ԵՒ ՊՐԻՆՍ" },
  { value: "SV", label: "SV — ՍԱԼՎԱԴՈՐ" },
  { value: "SX", label: "SX — ՍԻՆՏ ՄԱՐՏԵՆ" },
  { value: "SY", label: "SY — ՍԻՐԻԱ" },
  { value: "SZ", label: "SZ — ՍՎԱԶԻԼԵՆԴ" },
  { value: "TC", label: "TC — ՏԵՐԿՍ ԵՒ ԿԱՅԿՈՍ" },
  { value: "TD", label: "TD — ՉԱԴ" },
  { value: "TF", label: "TF — ՖՐ.ՀԱՐԱՎ.ՏԱՐԱԾՔ" },
  { value: "TG", label: "TG — ՏՈԳՈ" },
  { value: "TH", label: "TH — ԹԱԻԼԱՆԴ" },
  { value: "TJ", label: "TJ — ՏԱՋԻԿՍՏԱՆ" },
  { value: "TK", label: "TK — ՏՈԿԵԼԱՈՒ" },
  { value: "TL", label: "TL — ԱՐԵՒԵԼՅԱՆ ԹԻՄՈՐ" },
  { value: "TM", label: "TM — ԹՈՒՐՔՄԵՆՍՏԱՆ" },
  { value: "TN", label: "TN — ԹՈՒՆԻՍ" },
  { value: "TO", label: "TO — ՏՈՆԳԱ" },
  { value: "TR", label: "TR — ԹՈՒՐՔԻԱ" },
  { value: "TT", label: "TT — ՏՐԻՆԻԴԱԴ ԵՒ ՏՈԲԱԳՈ" },
  { value: "TV", label: "TV — ՏՈՒՎԱԼՈՒ" },
  { value: "TW", label: "TW — ԹԱՅՎԱՆ" },
  { value: "TZ", label: "TZ — ՏԱՆԶԱՆԻԱ" },
  { value: "UA", label: "UA — ՈՒԿՐԱԻՆԱ" },
  { value: "UG", label: "UG — ՈՒԳԱՆԴԱ" },
  { value: "UM", label: "UM — ՓՈՔ.ԽԱՂԱՂ ՕՎԿ.ԿՂԶԻՆԵՐ" },
  { value: "US", label: "US — ԱՄՆ" },
  { value: "UY", label: "UY — ՈՒՐՈՒԳՎԱՅ" },
  { value: "UZ", label: "UZ — ՈՒԶԲԵԿՍՏԱՆ" },
  { value: "VA", label: "VA — ՎԱՏԻԿԱՆ" },
  { value: "VC", label: "VC — ՍԵՆՏ-ՎԻՆՍԵՆՏ" },
  { value: "VE", label: "VE — ՎԵՆԵՍՈՒԵԼԱ" },
  { value: "VG", label: "VG — ԲՐԻՏԱՆԱԿԱՆ ՎԵՐՋԻՆՅԱՆ ԿՂԶԻՆԵՐ" },
  { value: "VI", label: "VI — ՎԵՐՋԻՆՅԱՆ ԿՂԶԻՆԵՐ" },
  { value: "VN", label: "VN — ՎԻԵՏՆԱՄ" },
  { value: "VU", label: "VU — ՎԱՆՈՒԱՏՈՒ" },
  { value: "WF", label: "WF — ՈՒՈԼԻՍ ԵՒ ՖՈՒՏՈՒՆԱ" },
  { value: "WS", label: "WS — ԱՐԵՒՄՏՅԱՆ ՍԱՄՈԱ" },
  { value: "YE", label: "YE — ԵՄԵՆ" },
  { value: "YT", label: "YT — ՄԱՅՈՏՏԱ" },
  { value: "ZA", label: "ZA — ՀԱՐԱՎ.ԱՖՐԻԿՅԱՆ ՀԱՆՐ." },
  { value: "ZM", label: "ZM — ԶԱՄԲԻԱ" },
  { value: "ZW", label: "ZW — ԶԻՄԲԱԲՎԵ" },
];

// code → Armenian name, so the writeback can fill `*CountryName` next to the code it writes.
const COUNTRY_NAME_BY_CODE = {
  "00": "ԵՐԿԻՐՆ ԱՆՀԱՅՏ Է",
  "AD": "ԱՆԴՈՐՐԱ",
  "AE": "ԱՐԱԲ.ՄԻԱՑ.ԷՄԻՐՈՒԹ.",
  "AF": "ԱՖՂԱՆՍՏԱՆ",
  "AG": "ԱՆՏԻԳՈՒԱ.ԲԱՐԲ.",
  "AI": "ԱՆԳԻԼՅԱ",
  "AL": "ԱԼԲԱՆԻԱ",
  "AM": "ՀԱՅԱՍՏԱՆ",
  "AO": "ԱՆԳՈԼԱ",
  "AQ": "ԱՆՏԱՐԿՏԻԴԱ",
  "AR": "ԱՐԳԵՆՏԻՆԱ",
  "AS": "ԱՐԵՒԵԼՅԱՆ ՍԱՄՈԱ (ԱՄՆ)",
  "AT": "ԱՎՍՏՐԻԱ",
  "AU": "ԱՎՍՏՐԱԼԻԱ",
  "AW": "ԱՐՈՒԲԱ",
  "AX": "ԱԼԱՆԴՅԱՆ ԿՂԶԻՆԵՐ",
  "AZ": "ԱԴՐԲԵՋԱՆ",
  "BA": "ԲՈՍՆԻԱ ԵՒ ՀԵՐՑԵԳՈՎԻՆԱ",
  "BB": "ԲԱՐԲԱԴՈՍ",
  "BD": "ԲԱՆԳԼԱԴԵՇ",
  "BE": "ԲԵԼԳԻԱ",
  "BF": "ԲՈՒՐԿԻՆԱ-ՖԱՍՈ",
  "BG": "ԲՈՒԼՂԱՐԻԱ",
  "BH": "ԲԱՀՐԵՅՆ",
  "BI": "ԲՈՒՐՈՒՆԴԻ",
  "BJ": "ԲԵՆԻՆ",
  "BL": "ՍԵՆ ԲԱՐՏԵԼՄԻ",
  "BM": "ԲԵՐՄՈՒԴՅԱՆ ԿՂԶԻՆԵՐ",
  "BN": "ԲՐՈՒՆԵՅ",
  "BO": "ԲՈԼԻՎԻԱ",
  "BQ": "ԲՈՆԱՅՐԵ, ՍԱԲԱ և ՍԻՆՏ ԷՍՏԱՏԻՈՒՍ",
  "BR": "ԲՐԱԶԻԼԻԱ",
  "BS": "ԲԱՀԱՄՅԱՆ ԿՂԶԻՆԵՐ",
  "BT": "ԲՈՒԹԱՆ",
  "BV": "ԲՈՒՎԵ",
  "BW": "ԲՈՏՍՎԱՆԱ",
  "BY": "ԲԵԼԱՌՈՒՍ",
  "BZ": "ԲԵԼԻԶ",
  "CA": "ԿԱՆԱԴԱ",
  "CC": "ԿՈԿՈՍՅԱՆ ԿՂԶԻՆԵՐ",
  "CD": "ԿՈՆԳՈ (ԿԴՀ)",
  "CF": "ԿԵՆՏ.ԱՖՐ.ՀԱՆՐ.",
  "CG": "ԿՈՆԳՈ",
  "CH": "ՇՎԵՅՑԱՐԻԱ",
  "CI": "ԿՈՏ Դ'ԻՎՈՒԱՐ",
  "CK": "ԿՈՒԿԻ ԿՂԶ.",
  "CL": "ՉԻԼԻ",
  "CM": "ԿԱՄԵՐՈՒՆ",
  "CN": "ՉԻՆԱՍՏԱՆ",
  "CO": "ԿՈԼՈՒՄԲԻԱ",
  "CR": "ԿՈՍՏԱ ՌԻԿԱ",
  "CU": "ԿՈՒԲԱ",
  "CV": "ԿԱԲՈ-ՎԵՐԴԵ",
  "CW": "ԿՅՈՒՐԱՍԱՈ",
  "CX": "ԾՆՆԴՅԱՆ ԿՂԶ.",
  "CY": "ԿԻՊՐՈՍ",
  "CZ": "ՉԵԽԻԱ",
  "DE": "ԳԵՐՄԱՆԻԱ",
  "DJ": "ՋԻԲՈՒԹԻ",
  "DK": "ԴԱՆԻԱ",
  "DM": "ԴՈՄԻՆԻԿԱ",
  "DO": "ԴՈՄԻՆԻԿՅԱՆ ՀԱՆՐ.",
  "DZ": "ԱԼԺԻՐ",
  "EC": "ԷԿՎԱԴՈՐ",
  "EE": "ԷՍՏՈՆԻԱ",
  "EG": "ԵԳԻՊՏՈՍ",
  "EH": "ԱՐԵՒՄՏՅԱՆ ՍԱՀԱՐԱ",
  "ER": "ԷՐԻԹՐԵԱ",
  "ES": "ԻՍՊԱՆԻԱ",
  "ET": "ԵԹՈՎՊԻԱ",
  "EU": "ԵՎՐՈՊԱԿԱՆ ՄԻՈՒԹՅՈՒՆ",
  "FI": "ՖԻՆԼԱՆԴԻԱ",
  "FJ": "ՖԻՋԻ",
  "FK": "ՖՈԼԿԼԵՆԴՅԱՆ ԿՂԶ.",
  "FM": "ՄԻԿՐՈՆԵԶԻԱ",
  "FO": "ՖԱՐԵՐՅԱՆ ԿՂԶ.",
  "FR": "ՖՐԱՆՍԻԱ",
  "GA": "ԳԱԲՈՆ",
  "GB": "ՄԵԾ ԲՐԻՏԱՆԻԱ",
  "GD": "ԳՐԵՆԱԴԱ",
  "GE": "ՎՐԱՍՏԱՆ",
  "GF": "ԳՎԻԱՆԱ",
  "GG": "ԳԵՐՆՍԻ",
  "GH": "ԳԱՆԱ",
  "GI": "ՋԻԲՐԱԼԹԱՐ",
  "GL": "ԳՐԵՆԼԱՆԴԻԱ",
  "GM": "ԳԱՄԲԻԱ",
  "GN": "ԳՎԻՆԵԱ",
  "GP": "ԳՎԱԴԵԼՈՒՊԱ",
  "GQ": "ՀԱՍԱՐԱԿԱԾԱՅԻՆ ԳՎԻՆԵԱ",
  "GR": "ՀՈՒՆԱՍՏԱՆ",
  "GS": "ՀԱՐԱՎԱՅԻՆ ՋՈՐՋԻԱ ԵՒ Հ. ՍԵՆԴՎԻՉ. ԿՂԶԻՆԵՐ",
  "GT": "ԳՎԱՏԵՄԱԼԱ",
  "GU": "ԳՈՒԱՄ (ԱՄՆ)",
  "GW": "ԳՎԻՆԵԱ-ԲԻՍԱՈՒ",
  "GY": "ԳԱՅԱՆԱ",
  "HK": "ՍՅԱՆԳԱՆ (ՀՈՆԿՈՆԳ)",
  "HM": "ԽԵՐԴ ԵՒ ՄԱԿԴՈՆԱԼԴ",
  "HN": "ՀՈՆԴՈՒՐԱՍ",
  "HR": "ԽՈՐՎԱԹԻԱ",
  "HT": "ՀԱԻԹԻ",
  "HU": "ՀՈՒՆԳԱՐԻԱ",
  "ID": "ԻՆԴՈՆԵԶԻԱ",
  "IE": "ԻՌԼԱՆԴԻԱ",
  "IL": "ԻՍՐԱՅԵԼ",
  "IM": "ՄԵՆ ԿՂԶ.",
  "IN": "ՀՆԴԿԱՍՏԱՆ",
  "IO": "ԲՐԻՏ.ՏԱՐ.ՀՆԴ.ՕՎԿ.",
  "IQ": "ԻՐԱՔ",
  "IR": "ԻՐԱՆ",
  "IS": "ԻՍԼԱՆԴԻԱ",
  "IT": "ԻՏԱԼԻԱ",
  "JE": "ՋԵՐՍԻ",
  "JM": "ՃԱՄԱՅԿԱ",
  "JO": "ՀՈՐԴԱՆԱՆ",
  "JP": "ՃԱՊՈՆԻԱ",
  "KE": "ՔԵՆԻԱ",
  "KG": "ՂՐՂԶՍՏԱՆ",
  "KH": "ԿԱՄԲՈՋԱ",
  "KI": "ԿԻՐԻԲԱՏԻ",
  "KM": "ԿՈՄՈՐՅԱՆ ԿՂԶԻՆԵՐ",
  "KN": "ՍԵՆՏ-ԿԻՏՍ ԵՒ ՆԵՎԻՍ",
  "KP": "ԿՈՐԵԱ (ԿԺԴՀ)",
  "KR": "ԿՈՐԵԱՅԻ ՀԱՆՐԱՊԵՏ.",
  "KW": "ՔՈՒՎԵՅԹ",
  "KY": "ԿԱՅՄԱՆԻ ԿՂԶ.",
  "KZ": "ՂԱԶԱԽՍՏԱՆ",
  "LA": "ԼԱՈՍ",
  "LB": "ԼԻԲԱՆԱՆ",
  "LC": "ՍԵՆՏ-ԼՅՈՒՍԻԱ",
  "LI": "ԼԻԽՏԵՆՇՏԵՅՆ",
  "LK": "ՇՐԻ-ԼԱՆԿԱ",
  "LR": "ԼԻԲԵՐԻԱ",
  "LS": "ԼԵՍՈՏՈ",
  "LT": "ԼԻՏՎԱ",
  "LU": "ԼՅՈՒՔՍԵՄԲՈՒՐԳ",
  "LV": "ԼԱՏՎԻԱ",
  "LY": "ԼԻԲԻԱ",
  "MA": "ՄԱՐՈԿԿՈ",
  "MC": "ՄՈՆԱԿՈ",
  "MD": "ՄՈԼԴՈՎԱ",
  "ME": "ՄՈՆՏԵՆԵԳՐՈ",
  "MF": "ՍԵՆ ՄԱՐՏԵՆ (ՖՐ.)",
  "MG": "ՄԱԴԱԳԱՍԿԱՐ",
  "MH": "ՄԱՐՇԱԼՅԱՆ ԿՂԶ.",
  "MK": "ՀՅՈՒՍԻՍԱՅԻՆ ՄԱԿԵԴՈՆԻԱ",
  "ML": "ՄԱԼԻ",
  "MM": "ՄՅԱՆՄԱ",
  "MN": "ՄՈՆՂՈԼԻԱ",
  "MO": "ԱՈՄԻՆ",
  "MP": "ՄԱՐԻԱՆՅԱՆ ԿՂԶԻՆԵՐ",
  "MQ": "ՄԱՐՏԻՆԻԿԱ",
  "MR": "ՄԱՎՐԻՏԱՆԻԱ",
  "MS": "ՄՈՆՏՍԵՐԱՏ",
  "MT": "ՄԱԼԹԱ",
  "MU": "ՄԱՎՐԻԿԻՈՍ",
  "MV": "ՄԱԼԴԻՎՅԱՆ ԿՂԶ.",
  "MW": "ՄԱԼԱՎԻ",
  "MX": "ՄԵՔՍԻԿԱ",
  "MY": "ՄԱԼԱՅԶԻԱ",
  "MZ": "ՄՈԶԱՄԲԻԿ",
  "NA": "ՆԱՄԻԲԻԱ",
  "NC": "ՆՈՐ ԿԱԼԵԴՈՆԻԱ",
  "NE": "ՆԻԳԵՐ",
  "NF": "ՆՈՐՖՈԼԿ",
  "NG": "ՆԻԳԵՐԻԱ",
  "NI": "ՆԻԿԱՐԱԳՈՒԱ",
  "NL": "ՆԻԴԵՌԼԱՆԴՆԵՐ",
  "NO": "ՆՈՐՎԵԳԻԱ",
  "NP": "ՆԵՊԱԼ",
  "NR": "ՆԱՈՒՐՈՒ",
  "NU": "ՆԻՈՒԵ",
  "NZ": "ՆՈՐ ԶԵԼԱՆԴԻԱ",
  "OM": "ՕՄԱՆ",
  "PA": "ՊԱՆԱՄԱ",
  "PE": "ՊԵՐՈՒ",
  "PF": "ՖՐ.ՊՈԼԻՆԵԶԻԱ",
  "PG": "ՊԱՊՈՒԱ ՆՈՐ ԳՎԻՆԵԱ",
  "PH": "ՖԻԼԻՊԻՆՆԵՐ",
  "PK": "ՊԱԿԻՍՏԱՆ",
  "PL": "ԼԵՀԱՍՏԱՆ",
  "PM": "ՍԵՆ-ՊՅԵՐ ԵՒ ՄԻԿԵԼՈՆ",
  "PN": "ՊԻՏԿԵՐՆ",
  "PR": "ՊՈՒԵՐՏՈ ՌԻԿՈ",
  "PS": "ՊԱՂԵՍՏԻՆ, ՕԿՈՒՊԱՑՎԱԾ",
  "PT": "ՊՈՐՏՈՒԳԱԼԻԱ",
  "PW": "ՊԱԼԱՈՒ",
  "PY": "ՊԱՐԱԳՎԱՅ",
  "QA": "ԿԱՏԱՐ",
  "RE": "ՌԵՅՈՒՆՅՈՆ",
  "RO": "ՌՈՒՄԻՆԻԱ",
  "RS": "ՍԵՐԲԻԱ",
  "RU": "ՌՈՒՍԱՍՏԱՆ",
  "RW": "ՌՈՒԱՆԴԱ",
  "SA": "ՍԱՈՒԴՅԱՆ ԱՐԱԲԻԱ",
  "SB": "ՍՈՂՈՄՈՆՅԱՆ ԿՂԶ.",
  "SC": "ՍԵՅՇԵԼՅԱՆ ԿՂԶ.",
  "SD": "ՍՈՒԴԱՆ",
  "SE": "ՇՎԵԴԻԱ",
  "SG": "ՍԻՆԳԱՊՈՒՐ",
  "SH": "ՍՈՒՐԲ ՀԵՂԻՆԵԻ ԿՂԶ.",
  "SI": "ՍԼՈՎԵՆԻԱ",
  "SJ": "ՇՊԻՑԲԵՐԳԵՆ ԵՒ ՅԱՆՄԱՅԼԵՆ",
  "SK": "ՍԼՈՎԱԿԻԱ",
  "SL": "ՍՅԵՌԱ ԼԵՈՆԵ",
  "SM": "ՍԱՆ-ՄԱՐԻՆՈ",
  "SN": "ՍԵՆԵԳԱԼ",
  "SO": "ՍՈՄԱԼԻ",
  "SR": "ՍՈՒՐԻՆԱՄ",
  "SS": "ՀԱՐԱՎԱՅԻՆ ՍՈՒԴԱՆ",
  "ST": "ՍԱՆ-ՏՈՄԵ ԵՒ ՊՐԻՆՍ",
  "SV": "ՍԱԼՎԱԴՈՐ",
  "SX": "ՍԻՆՏ ՄԱՐՏԵՆ",
  "SY": "ՍԻՐԻԱ",
  "SZ": "ՍՎԱԶԻԼԵՆԴ",
  "TC": "ՏԵՐԿՍ ԵՒ ԿԱՅԿՈՍ",
  "TD": "ՉԱԴ",
  "TF": "ՖՐ.ՀԱՐԱՎ.ՏԱՐԱԾՔ",
  "TG": "ՏՈԳՈ",
  "TH": "ԹԱԻԼԱՆԴ",
  "TJ": "ՏԱՋԻԿՍՏԱՆ",
  "TK": "ՏՈԿԵԼԱՈՒ",
  "TL": "ԱՐԵՒԵԼՅԱՆ ԹԻՄՈՐ",
  "TM": "ԹՈՒՐՔՄԵՆՍՏԱՆ",
  "TN": "ԹՈՒՆԻՍ",
  "TO": "ՏՈՆԳԱ",
  "TR": "ԹՈՒՐՔԻԱ",
  "TT": "ՏՐԻՆԻԴԱԴ ԵՒ ՏՈԲԱԳՈ",
  "TV": "ՏՈՒՎԱԼՈՒ",
  "TW": "ԹԱՅՎԱՆ",
  "TZ": "ՏԱՆԶԱՆԻԱ",
  "UA": "ՈՒԿՐԱԻՆԱ",
  "UG": "ՈՒԳԱՆԴԱ",
  "UM": "ՓՈՔ.ԽԱՂԱՂ ՕՎԿ.ԿՂԶԻՆԵՐ",
  "US": "ԱՄՆ",
  "UY": "ՈՒՐՈՒԳՎԱՅ",
  "UZ": "ՈՒԶԲԵԿՍՏԱՆ",
  "VA": "ՎԱՏԻԿԱՆ",
  "VC": "ՍԵՆՏ-ՎԻՆՍԵՆՏ",
  "VE": "ՎԵՆԵՍՈՒԵԼԱ",
  "VG": "ԲՐԻՏԱՆԱԿԱՆ ՎԵՐՋԻՆՅԱՆ ԿՂԶԻՆԵՐ",
  "VI": "ՎԵՐՋԻՆՅԱՆ ԿՂԶԻՆԵՐ",
  "VN": "ՎԻԵՏՆԱՄ",
  "VU": "ՎԱՆՈՒԱՏՈՒ",
  "WF": "ՈՒՈԼԻՍ ԵՒ ՖՈՒՏՈՒՆԱ",
  "WS": "ԱՐԵՒՄՏՅԱՆ ՍԱՄՈԱ",
  "YE": "ԵՄԵՆ",
  "YT": "ՄԱՅՈՏՏԱ",
  "ZA": "ՀԱՐԱՎ.ԱՖՐԻԿՅԱՆ ՀԱՆՐ.",
  "ZM": "ԶԱՄԲԻԱ",
  "ZW": "ԶԻՄԲԱԲՎԵ",
};
