"""The filed format itself: every element name, every sequence, every constant, every facet.

This is the one place in DeepClare that spells the customs contract out. Dossier 04 §0
is the framing and it is not negotiable: the element names, their order, their
cardinality, the namespaces and the empty-versus-absent rules belong to an external
customs system. Deviations fail import with one opaque message that names no field, no
line and no reason. Nothing here is a design.

## Where each half of this module comes from

**Structure is evidence.** Element names, their namespace prefixes and every child
sequence come from `observed`, generated by reading all 71 ground-truth declarations in
the evaluation corpus. Not one of them is typed by hand here: every name constant below
is passed through `_attested`, which fails at import if the name appears in no filing,
and `SEQUENCES` and `REPEATABLE` are the evidence module's own tables. An earlier
revision of this file guessed 18 names and 14 sequences from the field specification's
section order and every one of the guesses that mattered was wrong — the shipment
container was missing altogether, which alone made every emitted file unimportable.

**Representation is specification.** The fixed tokens (`IM`, `40`, `00`, `000`, the `OO`
preference marker), the number and date rules, the fixed-width code discipline and the
physical shape of the file are dossier 03 §6, and the corpus corroborates all of them.

Three of the format's properties look like mistakes and are not:

* **The misspellings are the contract.** `CounryName`, `ESADout_CUConsigment`,
  `Pakage*`/`Paking*` are the schema's own spellings and are reproduced character for
  character. Correcting one produces a rejected file.
* **Order is enforced even where presence is not.** Every complex type is a sequence.
  Two optional siblings in the wrong order rejected the whole file — the confirmed case
  is packaging quantity emitted after packaging type — and the message named no element.
* **Fixed-width codes are strings.** `00`, `000`, `055`, the eight-digit office code.
  Parsing one as a number and writing it back destroys it, and nothing but literal
  discipline holds the widths.

## Where the evidence overrules the specification

Three statements in dossier 03 §6 and §9 do not survive contact with the corpus, and the
corpus wins because it is the artefact the portal accepts:

* nesting depth is **six**, not five — every goods item's packing sub-block sits at six
  in all 71 filings;
* a goods description of up to 603 characters is attested, so the schema's 250 is not
  carried as a cap of any kind;
* the two shipment-level cost elements the specification records as present in 311 of
  311 filings appear in **none** of the 71, so their absence is no longer flagged.

One statement survives as an open question rather than a rule: §6 says absence is always
omission and self-closing elements are unattested, and 2 of the 71 filings carry an empty
self-closing consignor address. This module never writes one; `conformance` reports one
it reads as unconfirmed rather than as a violation.
"""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict

from deepclare.filing import observed

# --- namespaces -----------------------------------------------------------------------

NAMESPACE_URI: dict[str, str] = {
    "ESADout_CU": "urn:customs.ru:Information:CustomsDocuments:ESADout_CU:5.10.0",
    "catESAD_cu": "urn:customs.ru:CUESADCommonAggregateTypesCust:5.10.0",
    "cat_ru": "urn:customs.ru:CommonAggregateTypes:5.10.0",
}
"""The three prefixes a filed declaration is written across, and the URI each binds to.

Which element sits under which is per element and is not guessable from the element's
meaning — `SupplementaryGoodsQuantity` is under the root schema's prefix and all three of
its children are under the common-types prefix. That mapping is `observed`.
"""

XSI_PREFIX = "xsi"
XSI_URI = "http://www.w3.org/2001/XMLSchema-instance"
SCHEMA_LOCATION = f"{NAMESPACE_URI['ESADout_CU']} ESADout_CU.xsd"

DOCUMENT_MODE_ID = "1006107E"
"""Root attribute. Schema-fixed; the only value in the evidence base."""

ROOT_ATTRIBUTES: tuple[tuple[str, str], ...] = (
    ("xmlns:ESADout_CU", NAMESPACE_URI["ESADout_CU"]),
    ("xmlns:catESAD_cu", NAMESPACE_URI["catESAD_cu"]),
    ("xmlns:cat_ru", NAMESPACE_URI["cat_ru"]),
    (f"xmlns:{XSI_PREFIX}", XSI_URI),
    ("DocumentModeID", DOCUMENT_MODE_ID),
    (f"{XSI_PREFIX}:schemaLocation", SCHEMA_LOCATION),
)
"""The root's attributes, in the order all 71 filings write them. Declaration order is
recorded as known-safe, but there is no reason to differ from the evidence."""


# --- element names --------------------------------------------------------------------
#
# Grouped by the block they belong to, in emission order. Spelling is contract, and every
# name is checked against the evidence base as this module loads.


def _attested(name: str) -> str:
    """A name, having confirmed a real filing carries it.

    The whole point of this indirection is that a name nobody has ever seen filed cannot
    reach the writer. The failure it prevents gives no diagnostic on the other side: an
    unknown element is rejected as wrong format, naming no element.
    """
    if name not in observed.NAMESPACE_PREFIX:
        raise ValueError(
            f"{name!r} appears in none of the {observed.CASE_COUNT} filings in the "
            "evidence base; regenerate `observed` from a filing that carries it rather "
            "than naming it here"
        )
    return name


def prefix_for(name: str) -> str:
    """The namespace prefix one element is written under."""
    prefix = observed.NAMESPACE_PREFIX.get(name)
    if prefix is None:
        raise ValueError(f"no filing in the evidence base carries an element {name!r}")
    return prefix


ROOT = _attested("ESADout_CU")
SHIPMENT = _attested("ESADout_CUGoodsShipment")

CUSTOMS_PROCEDURE = _attested("CustomsProcedure")
CUSTOMS_MODE_CODE = _attested("CustomsModeCode")
ORIGIN_COUNTRY_NAME_SHIPMENT = _attested("OriginCountryName")
SPECIFICATION_NUMBER = _attested("SpecificationNumber")
SPECIFICATION_LIST_NUMBER = _attested("SpecificationListNumber")
TOTAL_GOODS_NUMBER = _attested("TotalGoodsNumber")
TOTAL_PACKAGE_NUMBER = _attested("TotalPackageNumber")
TOTAL_SHEET_NUMBER = _attested("TotalSheetNumber")

CONSIGNOR = _attested("ESADout_CUConsignor")
CONSIGNEE = _attested("ESADout_CUConsignee")
RESPONSIBLE_PERSON = _attested("ESADout_CUFinancialAdjustingResponsiblePerson")
DECLARANT = _attested("ESADout_CUDeclarant")
ORGANIZATION_NAME = _attested("OrganizationName")
ORGANIZATION_FEATURES = _attested("RAOrganizationFeatures")
TAX_CODE = _attested("UNN")
ADDRESS = _attested("Address")
COUNTRY_CODE = _attested("CountryCode")
COUNTRY_NAME = _attested("CounryName")
STREET_HOUSE = _attested("StreetHouse")

GOODS_LOCATION = _attested("ESADout_CUGoodsLocation")
GOODS_LOCATION_INFORMATION_TYPE = _attested("InformationTypeCode")
GOODS_LOCATION_OFFICE = _attested("CustomsOffice")
GOODS_LOCATION_COUNTRY_CODE = _attested("CustomsCountryCode")

CONSIGNMENT = _attested("ESADout_CUConsigment")
CONTAINER_INDICATOR = _attested("ContainerIndicator")
DESTINATION_COUNTRY_CODE = _attested("DestinationCountryCode")
DESTINATION_COUNTRY_NAME = _attested("DestinationCountryName")
DEPARTURE_TRANSPORT = _attested("ESADout_CUDepartureArrivalTransport")
BORDER_TRANSPORT = _attested("ESADout_CUBorderTransport")
TRANSPORT_MODE_CODE = _attested("TransportModeCode")

CONTRACT_TERMS = _attested("ESADout_CUMainContractTerms")
CONTRACT_CURRENCY_CODE = _attested("ContractCurrencyCode")
TOTAL_INVOICE_AMOUNT = _attested("TotalInvoiceAmount")
TRADE_COUNTRY_CODE = _attested("TradeCountryCode")
DELIVERY_TERMS = _attested("CUESADDeliveryTerms")
DELIVERY_TERMS_CODE = _attested("DeliveryTermsStringCode")

GOODS_ITEM = _attested("ESADout_CUGoods")
GOODS_NUMERIC = _attested("GoodsNumeric")
GOODS_DESCRIPTION = _attested("GoodsDescription")
GROSS_WEIGHT = _attested("GrossWeightQuantity")
NET_WEIGHT = _attested("NetWeightQuantity")
INVOICED_COST = _attested("InvoicedCost")
COMMODITY_CODE = _attested("GoodsTNVEDCode")
ORIGIN_COUNTRY_CODE = _attested("OriginCountryCode")
ORIGIN_COUNTRY_NAME = _attested("OriginCountryName")
CUSTOMS_COST_METHOD = _attested("CustomsCostCorrectMethod")
PREFERENCES = _attested("Preferencii")
PREFERENCE_TAX = _attested("CustomsTax")
PREFERENCE_DUTY = _attested("CustomsDuty")
PREFERENCE_RATE = _attested("Rate")
SUPPLEMENTARY_QUANTITY = _attested("SupplementaryGoodsQuantity")
GOODS_QUANTITY = _attested("GoodsQuantity")
MEASURE_UNIT_NAME = _attested("MeasureUnitQualifierName")
MEASURE_UNIT_CODE = _attested("MeasureUnitQualifierCode")
GOODS_PACKAGING = _attested("ESADGoodsPackaging")
PACKAGE_QUANTITY = _attested("PakageQuantity")
PACKAGE_TYPE_CODE = _attested("PakageTypeCode")
PACKING_INFORMATION = _attested("PackingInformation")
PACKING_CODE = _attested("PackingCode")
PACKING_QUANTITY = _attested("PakingQuantity")
GOODS_PROCEDURE = _attested("ESADCustomsProcedure")
MAIN_MODE_CODE = _attested("MainCustomsModeCode")
PRECEDING_MODE_CODE = _attested("PrecedingCustomsModeCode")
GOODS_TRANSFER_FEATURE = _attested("GoodsTransferFeature")

FILLER = _attested("FilledPerson")
FILLER_SURNAME = _attested("PersonSurname")
FILLER_GIVEN_NAME = _attested("PersonName")


# --- sequences ------------------------------------------------------------------------

EVIDENCE_CASE_COUNT = observed.CASE_COUNT
"""How many accepted-shaped declarations the structural half of this module rests on."""

NAMESPACE_PREFIX_BY_NAME: dict[str, str] = observed.NAMESPACE_PREFIX
"""Every attested element name and the one prefix it is written under."""

SEQUENCES: dict[str, tuple[str, ...]] = observed.CHILD_ORDER
"""Container to its children in the order the contract requires, straight from the
evidence. Optionality does not relax order: a child may be absent, but the ones present
must appear in this order."""

REPEATABLE: frozenset[str] = observed.REPEATABLE
"""Elements that legitimately appear more than once under one parent. Everything else
appearing twice under one parent is a defect, not a variation."""

CONTAINERS: frozenset[str] = frozenset(SEQUENCES)
LEAVES: frozenset[str] = frozenset(observed.NAMESPACE_PREFIX) - CONTAINERS


# --- constants the contract fixes -----------------------------------------------------

PROCEDURE_IMPORT = "IM"
MODE_CODE_HOME_USE = "40"
PRECEDING_MODE_NONE = "00"
TRANSFER_FEATURE_NONE = "000"
SINGLE_SPECIFICATION = "1"
SINGLE_SHEET = "1"

NO_PREFERENCE = "OO"
"""Box 36, filed three times. Two ASCII letter O, byte-verified — **not** digit zero.

Dossier 03 §5.5: filing a preference the goods do not qualify for under-declares duty,
which is legally consequential; filing this marker merely over-declares and is corrected
on the portal. A duty preference is derivable from origin and is deliberately never
derived. All 2842 goods items in the evidence base carry the letter form.
"""

DOMESTIC_COUNTRY_CODE = "AM"
DOMESTIC_COUNTRY_NAME = "ՀԱՅԱՍՏԱՆ"
"""The importer is Armenian by definition on an IM/40 import into Armenia, and so is the
destination. Both are constants of this product's jurisdiction, not document data."""

ABSENT_ORGANIZATION_NAME = "-"
"""The only placeholder the contract tolerates, and only in four places.

Dossier 03 §6: a `-` in any schema-typed leaf is exactly what the portal rejects, and
every generated file of the placeholder era failed on it. The free-text organization
names of the four party blocks are the whole of the exception.
"""

PARTY_BLOCKS: tuple[str, ...] = (CONSIGNOR, CONSIGNEE, RESPONSIBLE_PERSON, DECLARANT)

PLACEHOLDER_PERMITTED_PATHS = frozenset(
    f"{ROOT}/{SHIPMENT}/{block}/{ORGANIZATION_NAME}" for block in PARTY_BLOCKS
)


# --- code and name pairs --------------------------------------------------------------

CODE_NAME_PAIRS: tuple[tuple[str, str, str], ...] = (
    (GOODS_ITEM, ORIGIN_COUNTRY_CODE, ORIGIN_COUNTRY_NAME),
    (CONSIGNMENT, DESTINATION_COUNTRY_CODE, DESTINATION_COUNTRY_NAME),
    (ADDRESS, COUNTRY_CODE, COUNTRY_NAME),
    (SUPPLEMENTARY_QUANTITY, MEASURE_UNIT_CODE, MEASURE_UNIT_NAME),
)
"""Parent, code element, name element. Emitted together or not at all: the portal keys on
the code and renders the name from it, so a name without its code is dropped on import
with no message at all.

The parent is part of each entry because `OriginCountryName` is half of a pair inside a
goods item and a lone element at shipment level, where box 16 has no code half. Keyed by
name alone, the shipment's origin country would be reported as a broken pair on every
document ever written. The evidence bears the pairing out: 10 goods items across the
corpus omit both halves and none omits one.
"""


# --- leaf facets ----------------------------------------------------------------------


class FacetKind(StrEnum):
    """The leaf types that are stable across schema versions and worth checking.

    Dossier 11 §6: the vendored schema set is the wrong version and produces false errors
    on genuinely valid files, so it transfers as a facet dictionary and never as an
    acceptance oracle. These five are the layer its own provenance note calls stable.
    """

    INTEGER = "integer"
    DECIMAL = "decimal"
    DATE = "date"
    TEXT = "text"
    CODE = "code"


class Facet(BaseModel):
    """What one leaf's value has to look like."""

    model_config = ConfigDict(frozen=True)

    kind: FacetKind
    max_length: int | None = None
    """A hard cap. One over-long value rejects the whole file, with no element named."""

    advisory_max_length: int | None = None
    """A cap the schema states and real accepted filings exceed. Reported, never failed."""

    pattern: str | None = None
    fixed: str | None = None
    allowed: tuple[str, ...] | None = None
    digits: int | None = None
    """Exact digit count for a fixed-width token, checked as characters so that
    zero-padding is preserved rather than normalised away."""


_TEXT = Facet(kind=FacetKind.TEXT)
_DECIMAL = Facet(kind=FacetKind.DECIMAL)
_INTEGER = Facet(kind=FacetKind.INTEGER)
_ALPHA2_COUNTRY = Facet(kind=FacetKind.CODE, pattern=r"^[A-Z]{2}$")

FACETS: dict[tuple[str | None, str], Facet] = {
    # Header.
    (ROOT, CUSTOMS_PROCEDURE): Facet(kind=FacetKind.CODE, fixed=PROCEDURE_IMPORT),
    (ROOT, CUSTOMS_MODE_CODE): Facet(kind=FacetKind.CODE, fixed=MODE_CODE_HOME_USE),
    # Shipment level.
    (SHIPMENT, ORIGIN_COUNTRY_NAME_SHIPMENT): _TEXT,
    (SHIPMENT, SPECIFICATION_NUMBER): Facet(
        kind=FacetKind.INTEGER, fixed=SINGLE_SPECIFICATION
    ),
    (SHIPMENT, SPECIFICATION_LIST_NUMBER): Facet(
        kind=FacetKind.INTEGER, fixed=SINGLE_SPECIFICATION
    ),
    (SHIPMENT, TOTAL_GOODS_NUMBER): _INTEGER,
    (SHIPMENT, TOTAL_PACKAGE_NUMBER): _DECIMAL,
    (SHIPMENT, TOTAL_SHEET_NUMBER): Facet(kind=FacetKind.INTEGER, fixed=SINGLE_SHEET),
    # Parties.
    (None, ORGANIZATION_NAME): Facet(kind=FacetKind.TEXT, advisory_max_length=150),
    (ORGANIZATION_FEATURES, TAX_CODE): Facet(
        kind=FacetKind.CODE, pattern=r"^[0-9]+$", advisory_max_length=8
    ),
    (ADDRESS, COUNTRY_CODE): _ALPHA2_COUNTRY,
    (ADDRESS, COUNTRY_NAME): _TEXT,
    (ADDRESS, STREET_HOUSE): Facet(kind=FacetKind.TEXT, max_length=50),
    # Goods location.
    (GOODS_LOCATION, GOODS_LOCATION_INFORMATION_TYPE): Facet(kind=FacetKind.CODE),
    (GOODS_LOCATION, GOODS_LOCATION_OFFICE): Facet(kind=FacetKind.CODE, digits=8),
    (GOODS_LOCATION, GOODS_LOCATION_COUNTRY_CODE): _ALPHA2_COUNTRY,
    # Consignment and transport.
    (CONSIGNMENT, CONTAINER_INDICATOR): Facet(
        kind=FacetKind.CODE, allowed=("true", "false")
    ),
    (CONSIGNMENT, DESTINATION_COUNTRY_CODE): Facet(
        kind=FacetKind.CODE, fixed=DOMESTIC_COUNTRY_CODE
    ),
    (CONSIGNMENT, DESTINATION_COUNTRY_NAME): Facet(
        kind=FacetKind.TEXT, fixed=DOMESTIC_COUNTRY_NAME
    ),
    (None, TRANSPORT_MODE_CODE): Facet(kind=FacetKind.CODE, pattern=r"^[0-9]{2}$"),
    # Contract terms.
    (CONTRACT_TERMS, CONTRACT_CURRENCY_CODE): Facet(
        kind=FacetKind.CODE, pattern=r"^[A-Z]{3}$"
    ),
    (CONTRACT_TERMS, TOTAL_INVOICE_AMOUNT): _DECIMAL,
    (CONTRACT_TERMS, TRADE_COUNTRY_CODE): _ALPHA2_COUNTRY,
    (DELIVERY_TERMS, DELIVERY_TERMS_CODE): _TEXT,
    # Goods item.
    (GOODS_ITEM, GOODS_NUMERIC): _INTEGER,
    # No length cap of any kind: the evidence base carries a 603-character description,
    # against the 250 the schema states. Dossier 03 §9 lists that overrun as an open
    # question and the corpus settles it.
    (GOODS_ITEM, GOODS_DESCRIPTION): _TEXT,
    (GOODS_ITEM, GROSS_WEIGHT): _DECIMAL,
    (GOODS_ITEM, NET_WEIGHT): _DECIMAL,
    (GOODS_ITEM, INVOICED_COST): _DECIMAL,
    (GOODS_ITEM, COMMODITY_CODE): Facet(kind=FacetKind.CODE, digits=11),
    (GOODS_ITEM, ORIGIN_COUNTRY_CODE): _ALPHA2_COUNTRY,
    (GOODS_ITEM, ORIGIN_COUNTRY_NAME): _TEXT,
    (GOODS_ITEM, CUSTOMS_COST_METHOD): Facet(
        kind=FacetKind.CODE, allowed=("0", "1", "2", "3", "4", "5", "6")
    ),
    (PREFERENCES, PREFERENCE_TAX): Facet(kind=FacetKind.CODE, fixed=NO_PREFERENCE),
    (PREFERENCES, PREFERENCE_DUTY): Facet(kind=FacetKind.CODE, fixed=NO_PREFERENCE),
    # `Rate` is a decimal tariff rate inside the payment block and a two-character
    # alphabetic code here. Dossier 07 §2.5 records the collision: any consumer must
    # resolve this element by parent, never by name — which is why this table is keyed
    # by parent in the first place.
    (PREFERENCES, PREFERENCE_RATE): Facet(kind=FacetKind.CODE, fixed=NO_PREFERENCE),
    (SUPPLEMENTARY_QUANTITY, GOODS_QUANTITY): _DECIMAL,
    (SUPPLEMENTARY_QUANTITY, MEASURE_UNIT_NAME): _TEXT,
    (SUPPLEMENTARY_QUANTITY, MEASURE_UNIT_CODE): Facet(kind=FacetKind.CODE, digits=3),
    (GOODS_PACKAGING, PACKAGE_QUANTITY): _DECIMAL,
    (GOODS_PACKAGING, PACKAGE_TYPE_CODE): Facet(
        kind=FacetKind.CODE, allowed=("0", "1", "2")
    ),
    (PACKING_INFORMATION, PACKING_CODE): Facet(kind=FacetKind.CODE),
    (PACKING_INFORMATION, PACKING_QUANTITY): _DECIMAL,
    (GOODS_PROCEDURE, MAIN_MODE_CODE): Facet(
        kind=FacetKind.CODE, fixed=MODE_CODE_HOME_USE
    ),
    (GOODS_PROCEDURE, PRECEDING_MODE_CODE): Facet(
        kind=FacetKind.CODE, fixed=PRECEDING_MODE_NONE
    ),
    (GOODS_PROCEDURE, GOODS_TRANSFER_FEATURE): Facet(
        kind=FacetKind.CODE, fixed=TRANSFER_FEATURE_NONE
    ),
    # Filler.
    (FILLER, FILLER_SURNAME): _TEXT,
    (FILLER, FILLER_GIVEN_NAME): _TEXT,
}


def facet_for(parent_name: str | None, local_name: str) -> Facet | None:
    """The facet for one leaf, resolved by parent first.

    Resolution order is deliberate. `Rate` means two different things in two different
    parents and a name-keyed lookup gets one of them wrong, so the parent-qualified entry
    always wins and the bare-name entry is only a fallback for leaves that genuinely mean
    the same thing wherever they appear.
    """
    keyed = FACETS.get((parent_name, local_name))
    if keyed is not None:
        return keyed
    return FACETS.get((None, local_name))


def _uncovered_leaves() -> tuple[str, ...]:
    """Every (container, leaf) the evidence attests and no facet describes.

    A leaf with no facet is a leaf nothing checks, which is the same silence the portal
    answers with. The evidence names every place a leaf can occur, so this is decidable
    rather than a matter of remembering.
    """
    return tuple(
        f"{parent}/{child}"
        for parent, children in SEQUENCES.items()
        for child in children
        if child in LEAVES and facet_for(parent, child) is None
    )


_UNCOVERED = _uncovered_leaves()
if _UNCOVERED:  # pragma: no cover - a construction error, caught at import
    raise ValueError(
        "these leaves are attested in the evidence base and no facet describes them, "
        f"so nothing would check their values: {', '.join(_UNCOVERED)}"
    )


# --- what the contract knows and this product never writes ----------------------------

NEVER_EMITTED = frozenset(
    {
        "ElectronicDocumentSign",
        "RegNumberDoc",
        "ExecutionDate",
        "ContractCurrencyRate",
        "TotalCustCost",
        "CustCostCurrencyCode",
        "AdditionalSign",
        "customsCostBeforeKdt",
    }
)
"""Elements dossier 03 §5.8 records in filed declarations, that appear in none of the 71
ground truths, and that this product never produces.

Kept for the **read** direction only, so that meeting one in a document from outside is
recognised as expected rather than reported as noise. The registration trio is assigned
by the portal on registration. The currency rate the portal fills. The additional-sign
marker has no recorded trigger. `customsCostBeforeKdt` is an un-namespaced, camelCase
post-filing correction artifact that the portal's own exports contain.

`TotalCustCost` and `CustCostCurrencyCode` were the uncomfortable pair — recorded as
present in all 311 filings of the earlier profile and never emitted. They occur in none
of the 71 ground truths, which is why conformance no longer reports their absence.
"""

READ_ONLY_ELEMENTS = frozenset(
    {
        "ContainerIdentificaror",
        "MeasureUnitCode",
        "PresentedDocument",
        "PaymentCalculation",
    }
)
"""Names that appear in filed declarations and never in ours. Kept so the read direction
recognises them as known rather than reporting them as unmapped noise."""

CONTRACT_CONSTANTS = frozenset(
    {
        CUSTOMS_PROCEDURE,
        CUSTOMS_MODE_CODE,
        SPECIFICATION_NUMBER,
        SPECIFICATION_LIST_NUMBER,
        TOTAL_SHEET_NUMBER,
        DESTINATION_COUNTRY_CODE,
        DESTINATION_COUNTRY_NAME,
        PREFERENCES,
        PREFERENCE_TAX,
        PREFERENCE_DUTY,
        PREFERENCE_RATE,
        GOODS_PROCEDURE,
        MAIN_MODE_CODE,
        PRECEDING_MODE_CODE,
        GOODS_TRANSFER_FEATURE,
    }
)
"""Elements whose value the domain never chooses. The write direction supplies them from
this module; the read direction has nothing to map them to, which is not a loss."""

MAX_NESTING_DEPTH = 6
"""Root, shipment, goods item, packaging, packing information, packing code. Dossier 03
§6 says five; all 71 filings say six, on every goods item."""

MAX_FILE_BYTES = 4 * 1024 * 1024
